# Site settings
title:          Tale
description:    "Be better perosn"
url:            "https://getww1092.github.io"

# Author
author:
  name:         Like_gg
  url:          https://github.com/getww1092
  email:        quaint3@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
